version: '3.3'

services:
  eform-dev:
    build: .
    ports:
      - "8079:8079"
    restart: always

    volumes:
      - /mnt/eform/languages:/app/locales
      - /mnt/eform/data:/app/data
      - /mnt/eform:/app/eform
      - /mnt/eform/datatest/out:/app/out

    environment:
      - PORT=8082
      - "8080:8082"
      - NODE_ENV=dev
      - DATA_DIR=/app/data
      - LOCALES_DIR=/app/locales
      - ROOT_DIR=/app/eform
      - OUTPUT_DIR=/app/out


